### ISSUE TITLE
`oauth-api-and-next-app-in-5-mins` - `env` should not be used outside of config files

### ISSUE THREAD

**Issue by sentisso** [tiagomichaelsousa/website#34]
In your tutorial there's a [code snippet](https://github.com/tiagomichaelsousa/website/blob/main/data/articles/oauth-api-and-next-app-in-5-mins/oauth-api-and-next-app-in-5-mins.mdx?plain=1#L292) with `redirect` that contains `env()` function (in `app/Http/Controllers/OAuthProviderController.php`).

Using this I receive this error after authorizing via github (and others):
![image](https://user-images.githubusercontent.com/38100632/192154957-9d0bf4b0-9342-4e4f-8c60-860aa131caa2.png)

This can be fixed by using `return redirect(config('app.frontend_url'));` instead of calling `env()` _(which shouldn't be used outside of the config files, according to [laracasts](https://laracasts.com/discuss/channels/laravel/middleware-error-argument-1-content-must-be-of-type-string?page=1&replyId=816581)_.

`'frontend_url' => env('FRONTEND_URL'),` should already be included in `config/app.php`

**Comment by tiagomichaelsousa** [comment]
Hey @sentisso, how are you? 👋

You are totally right, I will fix the blog post/tutorial and the code base!

Thank you for your feedback and for taking the time to warn me! 🙏

**Comment by sentisso** [comment]
No problem! Here to help others right?

Awesome tutorial btw, I thank you!
